runtime: python39
entrypoint: gunicorn -b :$PORT main:app

# instance_class: F2

# automatic_scaling:
#   target_cpu_utilization: 0.65
#   target_memory_utilization: 0.65

# env_variables:
#   VARIABLE_NAME: variable_value

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto